sudo: required
dist: trusty
language: node_js
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - nvm install 10
install:
  - yarn global add codecov
  - yarn
script:
  - yarn test
  - codecov
